version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: local_postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: qwe123
      POSTGRES_DB: fishing
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
  redis:
    image: redis:7
    container_name: local_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
  nats:
    image: nats:latest
    ports:
      - 4222:4222
      - 8222:8222
      - 6222:6222
    command: --jetstream --http_port 8222
    volumes:
      - nats-data:/data
    restart: unless-stopped
    networks:
      - nats-network
    environment:
      - NATS_SERVER_NAME=nats-server
  nats-box:
    image: natsio/nats-box:latest
    depends_on:
      - nats
    networks:
      - nats-network
    command: tail -f /dev/null
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: qwe123
      MYSQL_DATABASE: myapp
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: qwe123
networks:
  nats-network:
    driver: bridge
volumes:
  pg_data: null
  redis_data: {}
  nats-data: null
  mysql_data: {}
