version: '2'
services:
  local-mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: qwe123
      MYSQL_DATABASE: Test

