// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.6.0
// source: room/room.proto

package room

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NewRoomReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlatformId    string                 `protobuf:"bytes,1,opt,name=platform_id,json=platformId,proto3" json:"platform_id,omitempty"`
	RoomName      string                 `protobuf:"bytes,2,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	RoomType      string                 `protobuf:"bytes,3,opt,name=room_type,json=roomType,proto3" json:"room_type,omitempty"`
	BookDate      string                 `protobuf:"bytes,4,opt,name=book_date,json=bookDate,proto3" json:"book_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewRoomReq) Reset() {
	*x = NewRoomReq{}
	mi := &file_room_room_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewRoomReq) ProtoMessage() {}

func (x *NewRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_room_room_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewRoomReq.ProtoReflect.Descriptor instead.
func (*NewRoomReq) Descriptor() ([]byte, []int) {
	return file_room_room_proto_rawDescGZIP(), []int{0}
}

func (x *NewRoomReq) GetPlatformId() string {
	if x != nil {
		return x.PlatformId
	}
	return ""
}

func (x *NewRoomReq) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *NewRoomReq) GetRoomType() string {
	if x != nil {
		return x.RoomType
	}
	return ""
}

func (x *NewRoomReq) GetBookDate() string {
	if x != nil {
		return x.BookDate
	}
	return ""
}

type NewRoomResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlatformId    string                 `protobuf:"bytes,1,opt,name=platform_id,json=platformId,proto3" json:"platform_id,omitempty"`
	RoomName      string                 `protobuf:"bytes,2,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	RoomType      string                 `protobuf:"bytes,3,opt,name=room_type,json=roomType,proto3" json:"room_type,omitempty"`
	BookDate      string                 `protobuf:"bytes,4,opt,name=book_date,json=bookDate,proto3" json:"book_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewRoomResp) Reset() {
	*x = NewRoomResp{}
	mi := &file_room_room_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewRoomResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewRoomResp) ProtoMessage() {}

func (x *NewRoomResp) ProtoReflect() protoreflect.Message {
	mi := &file_room_room_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewRoomResp.ProtoReflect.Descriptor instead.
func (*NewRoomResp) Descriptor() ([]byte, []int) {
	return file_room_room_proto_rawDescGZIP(), []int{1}
}

func (x *NewRoomResp) GetPlatformId() string {
	if x != nil {
		return x.PlatformId
	}
	return ""
}

func (x *NewRoomResp) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *NewRoomResp) GetRoomType() string {
	if x != nil {
		return x.RoomType
	}
	return ""
}

func (x *NewRoomResp) GetBookDate() string {
	if x != nil {
		return x.BookDate
	}
	return ""
}

type GetRoomReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlatformId    string                 `protobuf:"bytes,1,opt,name=platform_id,json=platformId,proto3" json:"platform_id,omitempty"`
	RoomName      string                 `protobuf:"bytes,2,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomReq) Reset() {
	*x = GetRoomReq{}
	mi := &file_room_room_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomReq) ProtoMessage() {}

func (x *GetRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_room_room_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomReq.ProtoReflect.Descriptor instead.
func (*GetRoomReq) Descriptor() ([]byte, []int) {
	return file_room_room_proto_rawDescGZIP(), []int{2}
}

func (x *GetRoomReq) GetPlatformId() string {
	if x != nil {
		return x.PlatformId
	}
	return ""
}

func (x *GetRoomReq) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

type GetRoomResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlatformId    string                 `protobuf:"bytes,1,opt,name=platform_id,json=platformId,proto3" json:"platform_id,omitempty"`
	RoomName      string                 `protobuf:"bytes,2,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	RoomType      string                 `protobuf:"bytes,3,opt,name=room_type,json=roomType,proto3" json:"room_type,omitempty"`
	BookDate      string                 `protobuf:"bytes,4,opt,name=book_date,json=bookDate,proto3" json:"book_date,omitempty"`
	Participants  []string               `protobuf:"bytes,5,rep,name=participants,proto3" json:"participants,omitempty"` // List of participant IDs
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`             // e.g., "booked", "available", "cancelled"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoomResp) Reset() {
	*x = GetRoomResp{}
	mi := &file_room_room_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoomResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoomResp) ProtoMessage() {}

func (x *GetRoomResp) ProtoReflect() protoreflect.Message {
	mi := &file_room_room_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoomResp.ProtoReflect.Descriptor instead.
func (*GetRoomResp) Descriptor() ([]byte, []int) {
	return file_room_room_proto_rawDescGZIP(), []int{3}
}

func (x *GetRoomResp) GetPlatformId() string {
	if x != nil {
		return x.PlatformId
	}
	return ""
}

func (x *GetRoomResp) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *GetRoomResp) GetRoomType() string {
	if x != nil {
		return x.RoomType
	}
	return ""
}

func (x *GetRoomResp) GetBookDate() string {
	if x != nil {
		return x.BookDate
	}
	return ""
}

func (x *GetRoomResp) GetParticipants() []string {
	if x != nil {
		return x.Participants
	}
	return nil
}

func (x *GetRoomResp) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_room_room_proto protoreflect.FileDescriptor

const file_room_room_proto_rawDesc = "" +
	"\n" +
	"\x0froom/room.proto\x12\x04Room\"\x84\x01\n" +
	"\n" +
	"NewRoomReq\x12\x1f\n" +
	"\vplatform_id\x18\x01 \x01(\tR\n" +
	"platformId\x12\x1b\n" +
	"\troom_name\x18\x02 \x01(\tR\broomName\x12\x1b\n" +
	"\troom_type\x18\x03 \x01(\tR\broomType\x12\x1b\n" +
	"\tbook_date\x18\x04 \x01(\tR\bbookDate\"\x85\x01\n" +
	"\vNewRoomResp\x12\x1f\n" +
	"\vplatform_id\x18\x01 \x01(\tR\n" +
	"platformId\x12\x1b\n" +
	"\troom_name\x18\x02 \x01(\tR\broomName\x12\x1b\n" +
	"\troom_type\x18\x03 \x01(\tR\broomType\x12\x1b\n" +
	"\tbook_date\x18\x04 \x01(\tR\bbookDate\"J\n" +
	"\n" +
	"GetRoomReq\x12\x1f\n" +
	"\vplatform_id\x18\x01 \x01(\tR\n" +
	"platformId\x12\x1b\n" +
	"\troom_name\x18\x02 \x01(\tR\broomName\"\xc1\x01\n" +
	"\vGetRoomResp\x12\x1f\n" +
	"\vplatform_id\x18\x01 \x01(\tR\n" +
	"platformId\x12\x1b\n" +
	"\troom_name\x18\x02 \x01(\tR\broomName\x12\x1b\n" +
	"\troom_type\x18\x03 \x01(\tR\broomType\x12\x1b\n" +
	"\tbook_date\x18\x04 \x01(\tR\bbookDate\x12\"\n" +
	"\fparticipants\x18\x05 \x03(\tR\fparticipants\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status2f\n" +
	"\x04Room\x12.\n" +
	"\aNewRoom\x12\x10.Room.NewRoomReq\x1a\x11.Room.NewRoomResp\x12.\n" +
	"\aGetRoom\x12\x10.Room.GetRoomReq\x1a\x11.Room.GetRoomRespB\x11Z\x0fgrpc/proto/roomb\x06proto3"

var (
	file_room_room_proto_rawDescOnce sync.Once
	file_room_room_proto_rawDescData []byte
)

func file_room_room_proto_rawDescGZIP() []byte {
	file_room_room_proto_rawDescOnce.Do(func() {
		file_room_room_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_room_room_proto_rawDesc), len(file_room_room_proto_rawDesc)))
	})
	return file_room_room_proto_rawDescData
}

var file_room_room_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_room_room_proto_goTypes = []any{
	(*NewRoomReq)(nil),  // 0: Room.NewRoomReq
	(*NewRoomResp)(nil), // 1: Room.NewRoomResp
	(*GetRoomReq)(nil),  // 2: Room.GetRoomReq
	(*GetRoomResp)(nil), // 3: Room.GetRoomResp
}
var file_room_room_proto_depIdxs = []int32{
	0, // 0: Room.Room.NewRoom:input_type -> Room.NewRoomReq
	2, // 1: Room.Room.GetRoom:input_type -> Room.GetRoomReq
	1, // 2: Room.Room.NewRoom:output_type -> Room.NewRoomResp
	3, // 3: Room.Room.GetRoom:output_type -> Room.GetRoomResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_room_room_proto_init() }
func file_room_room_proto_init() {
	if File_room_room_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_room_room_proto_rawDesc), len(file_room_room_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_room_room_proto_goTypes,
		DependencyIndexes: file_room_room_proto_depIdxs,
		MessageInfos:      file_room_room_proto_msgTypes,
	}.Build()
	File_room_room_proto = out.File
	file_room_room_proto_goTypes = nil
	file_room_room_proto_depIdxs = nil
}
